### ISSUE TITLE
models folder missing,how to initiate generator object

### ISSUE THREAD

**Issue by ronakdedhia18** [smtiitm/Fastspeech2_HS#1]
While calling inference.py  we get below error :

    from models import Generator
ModuleNotFoundError: No module named 'models'

models folder is missing,how to initiate Generator object

**Comment by Devansh-Shah11** [comment]
Yeah, even I am facing the same issue
Were you able to solve?

**Comment by StephennFernandes** [comment]
do git lfs clone URL to download whole repo correctly.

**Comment by utkarsh2299** [comment]
so this issue comes when hifigan is not properly initialised (or is not in correct path). Please check. 

P.s. : We brought storage for this github repo  and uploaded all the models, so lfs was not needed. I'll check it again.
